---
title: '*agate*: Acoustic Glider Analysis Tools and Environment'
# subtitle: 
page-layout: full
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(fontawesome)
```


<!-- # Acoustic Glider Analysis Tools and Environment -->

`r fa(name = "calendar-check")` *Last Update: `r format(Sys.Date(), "%d %b %Y")`*

A collection of MATLAB-based tools for piloting passive acoustic gliders, processing glider positional and environmental data, and analyzing glider-collected passive acoustic data, particularly for surveys of marine mammals. 

This package is very much under development and is hosted and version controlled on [GitHub](https://github.com/sfregosi/agate-public). My hope is that I will maintain a [stable release](https://github.com/sfregosi/agate-public/releases) and then for those interested in the latest functionality, the GitHub repository can be cloned. For those interested in [contributing](contribute.html) to the package, I suggest creating a fork and using pull requests to contribute. Please contact me if you have any questions, feedback, or suggestions!

selene [dot] fregosi [at] noaa.gov or [report an issue on GitHub](https://github.com/sfregosi/agate-public/issues/new){target='_blank'}

## Background

These tools were initially developed for use with passive acoustic glider surveys conducted by the [OSU/NOAA CIMERS Bioacoustics Lab](https://cimers.oregonstate.edu/our-research){index='_blank'}. Initial development was for surveys using Seaglider platforms and either the Wideband Intelligent Signal Processor and Recorder (WISPR) or the Passive Miniaturized Acoustic Recorder XL (PMARXL) recording systems. 

NOAA's [Uncrewed Systems Operations Center (UxSOC)](https://www.omao.noaa.gov/uncrewed-systems/about-noaa-uncrewed-systems-operations) funded additional development into a more broadly applicable and user-friendly tool box that could be used by all interested in conducting glider-based passive acoustic surveys for marine mammals. 

**Ready? [Get started](https://sfregosi.github.io/agate-public/get-started.html)**

![Diagram showing the different components of __*agate*__. Tools can be broken up into two main categories: piloting tools, which are used for survey planning and execution, and processing tools which are used in post-mission analyses. The processing tools can further be broken up into flight, acoustic, and cetacean encounter processing tools. The cetacean encounter processing tools can incorporate externally identified cetacean detections (white balloon) or process on-board detections if available.](images/agate_workflow_2024-08-09.png){#fig-components width=75%}

## Dependencies

This code was either developed or most recently updated and tested with MATLAB version 2022b, but has undergone some testing with 2020b.  

#### MATLAB toolboxes

- Mapping Toolbox  
__*agate*__ requires the MATLAB Mapping toolbox. In the future, we may try modify the mapping tools to work with the freely available `m_map` package to make it more accessible, but are not there yet!

#### MATLAB File Exchange

This package requires a few resources from MATLAB File Exchange. They come packaged within the `utils/fileExchange` folder. More info about each can be found below:

- [SSH/SFTP/SCP For MATLAB (v2)](https://www.mathworks.com/matlabcentral/fileexchange/35409-ssh-sftp-scp-for-matlab-v2)  
<sub>*David Freedman (2023). SSH/SFTP/SCP For Matlab (v2), MATLAB Central File Exchange. Retrieved April 24, 2023.*</sub>
- [LatLon Distance](https://www.mathworks.com/matlabcentral/fileexchange/38812-latlon-distance)  
<sub>*M Sohrabinia (2023). LatLon distance, MATLAB Central File Exchange. Retrieved April 24, 2023.*</sub>
<!-- - [hline and vline](https://www.mathworks.com/matlabcentral/fileexchange/1039-hline-and-vline) -->
- [cmocean](https://www.mathworks.com/matlabcentral/fileexchange/57773-cmocean-perceptually-uniform-colormaps)  
<sub>*Thyng, Kristen, et al. “True Colors of Oceanography: Guidelines for Effective and Accurate Colormap Selection.” Oceanography, vol. 29, no. 3, The Oceanography Society, Sept. 2016, pp. 9–13, doi:10.5670/oceanog.2016.66.*</sub>
- [seawater_density](https://www.mathworks.com/matlabcentral/fileexchange/85900-seawater-density-from-salinity-temperature-and-pressure)  
<sub>*Gabriel Ruiz-Martinez (2023). Seawater density from salinity, temperature and pressure, MATLAB Central File Exchange. Retrieved April 24, 2023.* </sub>


#### Basemap rasters

A raster file is needed to plot bathymetry data on any of the maps. Detailed basemaps are available from [NCEI](https://www.ncei.noaa.gov/products/etopo-global-relief-model).  

There are tradeoffs in the resolution of basemap raster selected.

- High resolution basemaps are necessary for fine-scale piloting to ensure the glider does not hit the bottom, but they require manual export of a .tiff from NCEI. 15 arc second is the finest resolution option and can be extracted for the specific area of interest using the [ETOPO Grid Extract tool](https://www.ncei.noaa.gov/maps/grid-extract/). The smaller the area extracted, the faster it will load and plot. 
- Lower resolution may be sufficient for post-mission plotting. The global 60 arc second tiff is a good mid-resolution option that is easy, although slow, to download, import, and plot. Alternatively, 60 arc second resolution for just a specific area of interest can be extracted with the [ETOPO Grid Extract tool](https://www.ncei.noaa.gov/maps/grid-extract/) providing a smaller file size and faster loading/plotting.  

## Disclaimer

<sub>The scientific results and conclusions, as well as any views or opinions expressed herein, are those of the author(s) and do not necessarily reflect the views of NOAA or the Department of Commerce.</sub>

<sub>This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All NOAA GitHub project code is provided on an 'as is' basis and the user assumes responsibility for its use. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.</sub>

<sub>Software code created by U.S. Government employees is not subject to copyright in the United States (17 U.S.C. §105). The United States/Department of Commerce reserves all rights to seek and obtain copyright protection in countries other than the United States for Software authored in its entirety by the Department of Commerce. To this end, the Department of Commerce hereby grants to Recipient a royalty-free, nonexclusive license to use, copy, and create derivative works of the Software outside of the United States.</sub>
