---
title: "Plots"
subtitle: 'Overview of all plotting functions'
---

```{r, include = FALSE}
library(fontawesome)
```

Basic details for each plotting function are available within the standard MATLAB-type documentation in the header of each function and include a detailed description, info on input and output arguments, and examples. These details can be pulled up by typing `doc function` or `help function` within the MATLAB Command Window. 

This page will show example plots and provide a bit more detail. 

## Initialization

To run any of the `agate` plotting functions, the toolbox must be initialized with a configuration file. 

No configuration file yet? Go back to [Get started - Create configuration files](get-started.html#create-configuration-files). At a minimum, the configuration file must include the top *required* portion, as well as the *optional - plotting* section.

```default
% ensure agate is on the path

% initialize with specified configuration file, 'agate_config.cnf'
agate agate_config.cnf

% initialize with prompt to select configuration file
agate
```
Most of the plotting functions rely on a `pp` (piloting parameters) variable that is a large table with various outputs from the .nc and .log files compiled in one place. If this has already be created, it can be loaded directly. If not, use `extractPilotingParams` to build it. 

```default
% load existing pp table
load(fullfile(CONFIG.path.mission, 'flightStatus', ['diveTracking_' CONFIG.glider '.mat']))

% create new pp table
pp = extractPilotingParams(CONFIG, fullfile(CONFIG.path.mission, 'basestationFiles'), ...
fullfile(CONFIG.path.mission, 'flightStatus'), 0);
% zero as last argument creates it from scratch (does not load any previous tables)
save(fullfile(CONFIG.path.mission, 'flightStatus', ['diveTracking_' CONFIG.glider '.mat']), 'pp');

```

<sub>[Back to top](#)</sub>

## Piloting plots

### Battery remaining and PAM free space

### Humidity and pressure

### Voltage use by device

### Voltage use by device, normalized by dive duration

### Minimum voltage reported

### Maps

<sub>[Back to top](#)</sub>




